version: '2.2'
services:
  tidal-connect:
    image: edgecrush3r/tidal-connect:latest
    tty: true
    restart: always
    network_mode: host
    devices:
     - /dev/snd
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - /var/run/dbus:/var/run/dbus
    dns:
      - 8.8.8.8
